Add missing `const` declaration to variables in `populatedb.js`
As I was following this tutorial, this script failed on my setup with:
```
ReferenceError: authordetail is not defined
```
and similarly for `bookdetail` and `bookinstancedetail`.

Just adding a `const` declaration for each to fix.